version: 2
jobs:
  deploy-develop:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "80:d7:31:83:97:dd:04:fc:15:e5:d9:83:22:eb:89:1e"
      - run:
          name: Setup SSH Key Host
          command: |
            ssh-keyscan -H $SSH_HOST_DEVELOP >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            ssh $SSH_USER@$SSH_HOST_DEVELOP "cd zoobc-explorer-ui/ && ls -ltr && ./deploy.sh"

workflows:
  version: 2
  build:
    jobs:
      - deploy-develop:
          filters:
            branches:
              only: develop

